resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: controller
  newName: harbor.eng.nutanix.com/ncn-ci/cluster-api-provider-nutanix
  newTag: e2e-046a410fb98d1cec8fc792f2ac7559e6b8687617
